### ISSUE TITLE
Incorrect feature chosen

### ISSUE THREAD

**Issue by davidbelliott1** [learn-co-curriculum/dsc-linear-regression-lab#2]
## Link to Canvas
https://learning.flatironschool.com/courses/4936/quizzes/27006

## Issue Subtype

- [X ] Master branch code
- [ X] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```
Solution (click to reveal)
const (the intercept), piece_count, and max_age
```

### Concern
There is an error in the Linear Regression Cumulative lab.

In the section “Selecting Features Based on p-values” the solution code calls out

const, piece_count, and max_age as the three relevant features.

According to the summary table, it’s those two, and min_age

The error is present in both the master branch and the solution

## (Optional) Proposed Solution
change max_age to min_age

## What OS Are You Using?

- [x ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by hoffm386** [comment]
Resolved by https://github.com/learn-co-curriculum/dsc-linear-regression-lab/pull/4
Thanks for flagging!
